### PR TITLE
[WIP] Added License and Build badge in README.md

### PR DESCRIPTION
**Pull request by sumitkharche**
Fix for the issue #34

### CODE REVIEW

**Comment by koppor** [comment]
This fixed https://github.com/JabRef/blog.jabref.org/issues/34#issuecomment-541320578

**Comment by koppor** [comment]
Please provide a screenshot of how it looks

Normally, we place the labels next to the heading...

**Comment by koppor** [comment]
Thank you for starting with contribing. Please work on issues helping us to reduce effort. See for instance #36

**Comment by sumitkharche** [comment]
> Please provide a screenshot of how it looks
> 
> Normally, we place the labels next to the heading...

There is no heading in this repo so I added the badges in the top of readme

**Comment by koppor** [comment]
Then, please make the README awesome! How to add a blog entry is not described properly. Can you do it? At least, a heading could be added.

**Comment by sumitkharche** [comment]
> Then, please make the README awesome! How to add a blog entry is not described properly. Can you do it? At least, a heading could be added.

Added the heading.
For new blog entry instructions, should I add new section in readme or change description in Contribution.md file.

**Comment by koppor** [comment]
Remember to use markdown-lint -- https://github.com/DavidAnson/markdownlint

**Comment by koppor** [comment]
Make it a good experience. Maybe, just linking the contribution file is enough. The current README does just talk about a request. That text needs to be fixed.

Please also review the contribution file. Is it still required to name the file properly?

**Pull request closed without merging**
