### PR TITLE
Add link to Subhramit GSoC project to AI blog post

### PR DESCRIPTION
**Pull request by InAnYan**
But, I'm not sure if it's right to edit the post after the posting date...

### CODE REVIEW

**Comment by mlep** [comment]
If you mention it (e.g. "Post updated on XXXX  - link to blahblahblah added."), it is perfectly fine.

**Comment by Siedlerchr** [comment]
I would not mention the other projects. The blog post is about your project and it's independent. All posts are tagged with GSoC so one can easily find them

**Comment by InAnYan** [comment]
Ah, okaty then :)

**Comment by InAnYan** [comment]
Ah, okay then :)

**Pull request closed without merging**
